cookie:
  expiry_days: 30
  key: some_signature_key
  name: IEEE-VT-OCS_authenticationkey
credentials:
  usernames:
    2btharp05:
      email: 2brett.m.tharp@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Brett Tharp
      password: $2b$12$0MtC0NE0rhNXrtwZNZQTCesEshTT9snoH9.hCmEjJRvL/CakH8/5q
    btharp05:
      email: brett.m.tharp@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Brett Tharp
      password: $2b$12$RxrBCWMp7K5S7mEtN5lkFOUsmvbBMP7TjXQ0jPh.2Q.XfD9JSkp0C
    btharp051:
      email: 1brett.m.tharp@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Brett Tharp
      password: $2b$12$82Y/o189Gmretgh0zdyunuNj0ww2d2idhgregFk2jL3YhU291zh6i
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$GqcmJLItWG6Dv5HN48dA7OAe1.4rORC0rtwmg3P8vIqMr7OnN0J7G
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$HyuWhb6Ysj5p55soPqZ3Iu54wJ4ttkuPyxhLIzcCozGO7.27WeAP6
pre-authorized:
  emails: null
